cp odm/bin/hw/vendor.oplus.hardware.charger-V1-service proprietary --parents
cp odm/etc/init/vendor.oplus.hardware.charger-V1-service.rc proprietary --parents
cp odm/lib/vendor.oplus.hardware.charger-V1-ndk.so proprietary --parents
cp odm/lib64/vendor.oplus.hardware.charger-V1-ndk.so proprietary --parents
cp product/etc/libnfc-nci.conf proprietary --parents
cp system_ext/etc/permissions/com.motorola.frameworks.core.addon.xml proprietary --parents
cp system_ext/lib/vendor.qti.hardware.trustedui@1.0.so proprietary --parents
cp system_ext/lib/vendor.qti.qesdhalaidl-V1-ndk.so proprietary --parents
cp system_ext/lib64/vendor.qti.hardware.qxr-V2-ndk_platform.so proprietary --parents
cp system_ext/lib64/vendor.qti.hardware.trustedui@1.0.so proprietary --parents
cp system_ext/lib64/vendor.qti.qesdhalaidl-V1-ndk.so proprietary --parents
cp vendor/bin/hw/android.hardware.cas@1.2-service proprietary --parents
cp vendor/etc/init/android.hardware.cas@1.2-service.rc proprietary --parents
cp vendor/lib/hw/audio.bluetooth.default.so proprietary --parents
cp vendor/lib/rfsa/adsp/libvpt_action_recognition.so proprietary --parents
cp vendor/lib/vendor.oplus.hardware.radio-V1-ndk_platform.so proprietary --parents
cp vendor/lib/vendor.pixelworks.hardware.display-V1-ndk.so proprietary --parents
cp vendor/lib64/hw/audio.bluetooth.default.so proprietary --parents
cp vendor/lib64/vendor.oplus.hardware.radio-V1-ndk_platform.so proprietary --parents
cp vendor/lib64/vendor.pixelworks.hardware.display-V1-ndk.so proprietary --parents
cp system_ext/framework/com.motorola.frameworks.core.addon.jar proprietary --parents
cp system_ext/framework/com.motorola.motosignature.jar proprietary --parents
cp system_ext/framework/moto-checkin.jar proprietary --parents
cp system_ext/framework/moto-settings.jar proprietary --parents
cp system_ext/framework/moto.jar proprietary --parents
cp vendor/etc/vintf/manifest/android.hardware.cas@1.2-service.xml proprietary --parents
